Repository aaryahjolia/dsa_competitive-coding, pull requests merged in 2022-07, with the labels that each got.

#16 Adding a descriptive designed readme
  Readme.md
Labels: HSOC22, HSOC22-Level-2

#17 Reverse array in groups.md
  Arrays/Reverse array in groups.md
Labels: HSOC22-Level-1, HSOC22

#31 Binary Tree Traversal #27
  Tree/Inorder_Traversal.md
  Tree/Postorder_Traversal.md
  Tree/Preorder_Traversal.md
Labels: HSOC22-Level-2

#62 Add LeetCode Tree Problem #54
  Tree/Invert_Binary_Tree.md
  Tree/Same_Tree.md
  Tree/Symmetric_Tree.md
Labels: HSOC22, HSOC22-Level-2

#56 Sudoku solver
  Backtracking/Sudoku_Solver.md
Labels: HSOC22-Level-1, HSOC22
